name: Context testing
on: workflow_dispatch
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Git output write
        id: step1
        run: |
          echo "firstword=hello" >> $GITHUB_ENV        
      - name: Git output write multiple line
        id: step2
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV        
          curl https://example.lab >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV        
          
      - name: Git output read
        id: step3
        run: |
          echo '${{  env.firstword }}'
          echo '${{  env.JSON_RESPONSE }}'
  
